Feat/#30 회원가입 기능 구현
Fluffy-SharingCalendar/Backend pull request #36
Opened 2024-12-06 12:49 UTC by o-jeong

2024-12-06 13:41 UTC, yujeongkwon reviewed
정말 수고 많으셨습니다! 리뷰하면서 저도 제가 잘모르는 부분이 어느 지점인지 깨닫게 된 것 같아요. 같이 공부하면서 프로젝트 더 발전시켜나갑시다✨

2024-12-06 13:41 UTC, yujeongkwon commented on src/main/java/com/fluffy/SharingCalendar/config/SecurityConfig.java
> +        return new BCryptPasswordEncoder();
패스워드 암호화 좋아용👍🏻

2024-12-06 13:41 UTC, yujeongkwon commented on src/main/java/com/fluffy/SharingCalendar/user/controller/UserController.java
> +        userService.registerUser(requestDto);
현재 컨트롤러가회원가입하는 서비스의 내부 구조를 너무 많이 알고 있는 것 같아요. 서비스에서 registerUser()라는 메서드를 하나 만들어서 묶어주는 것이 더 좋지 않을까요?

2024-12-06 13:41 UTC, yujeongkwon commented on src/main/java/com/fluffy/SharingCalendar/user/dto/SecurityAnswerDto.java
> +public class SecurityAnswerDto {
이전에 제가 날린 PR에서도 DTO에서 final 관련 키워드에 대해서 얘기 나눠었는데요. Dto에서 변경되지 않을 때, final 클래스를 웬만하면 쓰면 좋겠다 생각했는데 이게 또 마구 잡이로 쓰면 안되는 것 같더라고요! 관련자료 나눠봐용!

https://konghana01.tistory.com/594

2024-12-06 13:41 UTC, yujeongkwon commented on src/main/java/com/fluffy/SharingCalendar/user/service/UserService.java
> +                .orElseThrow(() -> new CustomException(USER_NOT_FOUND));
위의 findByLoginId() 재활용하면 좋을 것 같아요! findByLoginId()의 매개변수명만 수정하면 똑같아보여요

2024-12-06 13:41 UTC, yujeongkwon commented on src/main/java/com/fluffy/SharingCalendar/user/service/UserService.java
서비스 계층에서는 보통 습관적으로 데이터 일관성을 지켜줄 수 있는 @Transactional 을 사용하는 것이 좋을 것 같아요! 
근데 저도 자세한 원리 및 사용법을 잘 모르고 해당 어노테이션을 사용했는데 이번에 프로젝트 진행하면서 이에 대해 각자 알아보고 이후에 얘기 나누면서 @Transactional을 제대로 활용해봐요!

2024-12-06 13:41 UTC, yujeongkwon commented on src/main/java/com/fluffy/SharingCalendar/user/service/UserService.java
> +                    return buildSecurityAnswer(securityAnswerDto, user, securityQuestion);
securityQuestion를 buildSecurityAnswer() 매개변수에 인라인화하는 것 보다 해당 방식이 더 가독성이 좋아서 이렇게 지역 변수를 추가한 것 일까요?

2024-12-06 13:41 UTC, yujeongkwon commented on src/main/java/com/fluffy/SharingCalendar/user/service/UserService.java
> +    private SecurityAnswer buildSecurityAnswer(SecurityAnswerDto securityAnswerDto, User user, SecurityQuestion securityQuestion) {
buildSecurityAnswer 보다 createSecurityAnswer가 다른 메서드명이랑 더 일관성 있어보이는데 어떻게 생각하시나요!?

2024-12-06 13:44 UTC, yujeongkwon requested changes
빌드에 실패했습니다.😥 PR을 닫습니다.

2024-12-06 13:47 UTC, o-jeong commented on src/main/java/com/fluffy/SharingCalendar/user/service/UserService.java
> +    private SecurityAnswer buildSecurityAnswer(SecurityAnswerDto securityAnswerDto, User user, SecurityQuestion securityQuestion) {
위에 본인확인 질문 대답들을 만드는 메서드인 createSecurityAnswers와 헷갈릴 것 같아서 이렇게 만들었는데 그래도 buildSecurityAnswer가 좀 더 나을까용?!

2024-12-06 13:53 UTC, yujeongkwon commented
빌드에 성공했습니다.😊

2024-12-06 13:54 UTC, yujeongkwon commented
빌드에 성공했습니다.😊

2024-12-07 06:46 UTC, o-jeong commented on src/main/java/com/fluffy/SharingCalendar/user/controller/UserController.java
> +        userService.registerUser(requestDto);
검증 부분을 기존의 registerUser 메서드에 넣는게 맞을 것 같네요! 감사합니다 :)

2024-12-07 06:46 UTC, o-jeong commented on src/main/java/com/fluffy/SharingCalendar/user/dto/SecurityAnswerDto.java
> +public class SecurityAnswerDto {
좋은 자료 감사합니다! final에 대해 좀 더 공부하고 잘 적용해보도록 할게요 😀

2024-12-07 06:46 UTC, o-jeong commented on src/main/java/com/fluffy/SharingCalendar/user/service/UserService.java
@transactional 을 어떻게 쓰는지 잘 몰랐는데, 유정님 덕분에 @transactional이 어떻게 동작하도록 하는지, 어떤 장점을 가지는지 알 수 있게 된 것 같아요! 감사합니다  ㅎㅎ

2024-12-07 06:46 UTC, o-jeong commented on src/main/java/com/fluffy/SharingCalendar/user/service/UserService.java
> +                .orElseThrow(() -> new CustomException(USER_NOT_FOUND));
유정님께서 만드신 메서드라 findByLoginId()가 있는지 병합하고 확인했네요 ㅎㅎ 잘 사용하겠습니다 ㅎㅎ 😁

2024-12-07 06:46 UTC, o-jeong commented on src/main/java/com/fluffy/SharingCalendar/user/service/UserService.java
> +                    return buildSecurityAnswer(securityAnswerDto, user, securityQuestion);
넹 해당 질문, 대답, 사용자로 본인확인 질문 대답 객체를 만든다는 의미를 명확하게 하고 싶었습니다!

2024-12-07 06:46 UTC, yujeongkwon commented
빌드에 성공했습니다.😊

2024-12-07 06:56 UTC, yujeongkwon commented
> 정말 수고 많으셨습니다! 리뷰하면서 저도 제가 잘모르는 부분이 어느 지점인지 깨닫게 된 것 같아요. 같이 공부하면서 프로젝트 더 발전시켜나갑시다✨

2024-12-07 06:57 UTC, yujeongkwon approved these changes

2024-12-07 06:57 UTC, merged